# Created using wingetcreate 1.2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Tizen.TizenStudioCLI
PackageVersion: 5.1
PackageLocale: en-US
Publisher: Tizen
PackageName: TizenStudioCLI
License: TIZEN STUDIO LICENSE AGREEMENT
LicenseUrl: https://developer.tizen.org/tizen-sdk-license-agreement
ShortDescription: Tizen Studio CLI
ManifestType: defaultLocale
ManifestVersion: 1.4.0
